### ISSUE TITLE
Add disclaimer checkboxes to account request form

### ISSUE THREAD

**Issue by buske** [phenotips/phenomecentral.org#58]
[ ] PhenomeCentral provides data in good faith as a research tool, but without verifying the accuracy, clinical validity or utility of the data. PhenomeCentral makes no warranty, express or implied, nor assumes any legal liability or responsibility for any purpose for which the data are used. 

[ ] The user certifies that no attempt to identify individual patients will be undertaken.

[ ] Prior to using PhenomeCentral data in a publication, the user will contact the owner of the matching dataset to assess the integrity of the match and if validated will offer appropriate agreed recognition of their contribution, which may include co-authorship if the magnitude of the contribution warrants it to at least one representative from the project/participating centre (possibly the member who submitted the patient data). 

[ ] If PhenomeCentral enables a research publication, the authors must acknowledge PhenomeCentral using the following wording: "This study makes use of data shared through the PhenomeCentral repository. Funding for PhenomeCentral was provided by Genome Canada and Canadian Institute of Health Research (CIHR)."

**Comment by bgallinger** [comment]
What is the status on this? I need it added for my PC ethics application

**Comment by antonkatz** [comment]
It's done, but not on phenomecentral. Also no one checked the code.
